import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import rateLimit from "express-rate-limit";
import { env } from "./lib/config.js";
import { prisma } from "./lib/prisma.js";
import { authRouter } from "./routes/auth.js";
import { productRouter } from "./routes/products.js";
import { orderRouter } from "./routes/orders.js";
import { sellerRouter } from "./routes/seller.js";
import { adminRouter } from "./routes/admin.js";
import { subscriptionRouter } from "./routes/subscriptions.js";
import { payoutRouter } from "./routes/payouts.js";

const app=express();app.set("trust proxy",1);app.use(helmet());app.use(cors({origin:env.FRONTEND_URL,credentials:true}));app.use(cookieParser());app.use(express.json({limit:"2mb"}));
const apiLimit=rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false});app.use("/api",apiLimit);
app.get("/health",(_req,res)=>res.json({ok:true,service:"uzalink-api"}));
app.use("/api/auth",authRouter);app.use("/api/products",productRouter);app.use("/api/orders",orderRouter);app.use("/api/seller",sellerRouter);app.use("/api/admin",adminRouter);app.use("/api/subscriptions",subscriptionRouter);app.use("/api/payouts",payoutRouter);
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(err?.statusCode||500).json({error:env.NODE_ENV==="production"?"Something went wrong":err?.message||"Server error"});});
const server=app.listen(env.PORT,()=>console.log(`UzaLink API listening on ${env.PORT}`));
const shutdown=async()=>{server.close();await prisma.$disconnect();process.exit(0)};process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);
