import { Router } from "express";
import { z } from "zod";
import crypto from "node:crypto";
import { prisma } from "../lib/prisma.js";
import { createOrder, issueDownload } from "../services/orders.js";
import { stkPush } from "../services/mpesa.js";
import { requireAuth } from "../middleware/auth.js";
import { hashToken } from "../lib/auth.js";

export const orderRouter=Router();
orderRouter.post("/",async(req,res,next)=>{try{const b=z.object({productId:z.string().optional(),productCode:z.string().optional(),name:z.string().min(2),phone:z.string(),email:z.string().email().optional(),address:z.string().max(500).optional()}).parse(req.body);const product= b.productId ? await prisma.product.findUnique({where:{id:b.productId}}) : b.productCode ? await prisma.product.findUnique({where:{code:b.productCode}}) : null; if(!product) return res.status(404).json({error:"Product not found"}); const o=await createOrder(product.id,{name:b.name,phone:b.phone,email:b.email,address:b.address},req.user?.userId);res.status(201).json({order:o});}catch(e){next(e);}});
orderRouter.post("/:id/pay",async(req,res,next)=>{try{const order=await prisma.order.findUnique({where:{id:req.params.id},include:{items:{include:{product:true}}}});if(!order)return res.status(404).json({error:"Order not found"});if(order.status!=="PENDING")return res.status(409).json({error:"Order is not payable"});const payment=await prisma.payment.create({data:{orderId:order.id,amountCents:order.amountCents,phone:order.buyerPhone}});const mp=await stkPush({phone:order.buyerPhone,amountCents:order.amountCents,accountReference:order.publicId,description:order.items[0].product.name});await prisma.payment.update({where:{id:payment.id},data:{merchantRequestId:mp.MerchantRequestID,checkoutRequestId:mp.CheckoutRequestID}});res.json({orderId:order.id,publicId:order.publicId,checkoutRequestId:mp.CheckoutRequestID,message:mp.CustomerMessage});}catch(e){next(e);}});
orderRouter.get("/:id",async(req,res,next)=>{try{const o=await prisma.order.findUnique({where:{id:req.params.id},include:{payments:true,items:{include:{product:true}}}});if(!o)return res.status(404).json({error:"Order not found"});res.json({order:o});}catch(e){next(e);}});
orderRouter.post("/download/:token",async(req,res,next)=>{try{const ip=crypto.createHash("sha256").update(req.ip || "").digest("hex");const url=await issueDownload(req.params.token,ip,req.get("user-agent"));res.json({url});}catch(e){next(e);}});
orderRouter.get("/download/:token",async(req,res,next)=>{try{const ip=crypto.createHash("sha256").update(req.ip || "").digest("hex");const url=await issueDownload(req.params.token,ip,req.get("user-agent"));res.redirect(url);}catch(e){next(e);}});

// Daraja callback. This endpoint must be public and must never trust the browser.
orderRouter.post("/mpesa/callback",async(req,res,next)=>{try{const body=req.body?.Body?.stkCallback;const checkout=body?.CheckoutRequestID;res.json({ResultCode:0,ResultDesc:"Accepted"});if(!checkout)return;const payment=await prisma.payment.findUnique({where:{checkoutRequestId:checkout},include:{order:true}});if(!payment)return;if(Number(body.ResultCode)!==0){await prisma.payment.update({where:{id:payment.id},data:{status:"FAILED",resultCode:Number(body.ResultCode),resultDescription:body.ResultDesc,rawCallback:req.body}});await prisma.order.update({where:{id:payment.orderId},data:{status:"FAILED"}});return;}const meta=body.CallbackMetadata?.Item || [];const get=(name:string)=>meta.find((x:any)=>x.Name===name)?.Value;await prisma.payment.update({where:{id:payment.id},data:{resultCode:0,resultDescription:body.ResultDesc,rawCallback:req.body,receipt:String(get("MpesaReceiptNumber")||"")}});const subscription=await prisma.subscription.findUnique({where:{paymentId:payment.id}});
if(subscription){const starts=new Date();const ends=new Date(starts.getTime()+Number(process.env.PREMIUM_DURATION_DAYS||30)*86400000);await prisma.subscription.update({where:{id:subscription.id},data:{status:"ACTIVE",startsAt:starts,endsAt:ends}});await prisma.payment.update({where:{id:payment.id},data:{status:"SUCCESS",receipt:String(get("MpesaReceiptNumber")||"")}});return;}
const { fulfillPaidOrder }=await import("../services/orders.js");await fulfillPaidOrder(payment.orderId,payment.id,String(get("MpesaReceiptNumber")||""));}catch(e){next(e);}});
