import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { requireAuth, requireRole } from "../middleware/auth.js";
import { requirePremium } from "../middleware/premium.js";
import { normalizePhone } from "../services/mpesa.js";
import { sendSellerPayout } from "../services/payouts.js";

export const sellerRouter=Router();sellerRouter.use(requireAuth,requireRole("SELLER","ADMIN"));
sellerRouter.get("/dashboard",requirePremium,async(req,res,next)=>{try{const s=await prisma.sellerProfile.findUnique({where:{userId:req.user!.userId},include:{user:true,products:{orderBy:{createdAt:"desc"}},payouts:{orderBy:{createdAt:"desc"},take:20}}});if(!s)return res.status(404).json({error:"Seller profile not found"});const orders=await prisma.order.findMany({where:{items:{some:{product:{sellerId:s.id}}}},include:{items:{include:{product:true}},payments:true},orderBy:{createdAt:"desc"},take:50});res.json({seller:s,orders});}catch(e){next(e);}});
sellerRouter.post("/profile",async(req,res,next)=>{try{const b=z.object({handle:z.string().min(3).regex(/^[a-z0-9_]+$/),paymentNumber:z.string()}).parse(req.body);const phone=normalizePhone(b.paymentNumber);const existing=await prisma.sellerProfile.findUnique({where:{userId:req.user!.userId}});const s=existing?await prisma.sellerProfile.update({where:{id:existing.id},data:{handle:b.handle,paymentNumber:phone}}):await prisma.sellerProfile.create({data:{userId:req.user!.userId,handle:b.handle,paymentNumber:phone}});res.json({seller:s});}catch(e){next(e);}});
sellerRouter.post("/payout",requirePremium,async(req,res,next)=>{try{const b=z.object({amountCents:z.number().int().positive()}).parse(req.body);const s=await prisma.sellerProfile.findUnique({where:{userId:req.user!.userId}});if(!s)return res.status(404).json({error:"Seller profile not found"});if(b.amountCents>s.balanceCents)return res.status(400).json({error:"Insufficient available balance"});const p=await prisma.$transaction(async tx=>{await tx.sellerProfile.update({where:{id:s.id},data:{balanceCents:{decrement:b.amountCents},pendingCents:{increment:b.amountCents}}});return tx.payout.create({data:{sellerId:s.id,amountCents:b.amountCents,phone:s.paymentNumber}});});let mpesa;try{mpesa=await sendSellerPayout(p.id);}catch(err){await prisma.$transaction([prisma.payout.update({where:{id:p.id},data:{status:"FAILED"}}),prisma.sellerProfile.update({where:{id:s.id},data:{pendingCents:{decrement:b.amountCents},balanceCents:{increment:b.amountCents}}})]);throw err;}res.status(201).json({payout:p,mpesa});}catch(e){next(e);}});
